### ISSUE TITLE
I've added a status response for setting up DHCP - please merge my pull request!

### ISSUE THREAD

**Issue by MichaelJAndy** [csquared/arduino-restclient#15]
Love this library, looking forward to contributing more to it!
https://github.com/csquared/arduino-restclient/pull/14

**Comment by MichaelJAndy** [comment]
Also as a heads up I've changed my username: https://github.com/MichaelJAndy

**Comment by csquared** [comment]
Just merged!

**Comment by MichaelJAndy** [comment]
Thanks!
